name: Linux Clang
on:
  push:
    branches: main

jobs:
  ubuntu_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        clang-version: [ 10, 11, 12 ]
        BUILD_TYPE: [ Release, Debug, Profile ]
        exclude:
          # excludes clang-11 and clang-12 on Ubuntu 18.04 because it doesn't exist in the
          #standard repositories.
          - os: ubuntu-18.04
            clang-version: [ 11, 12 ]

    name: ${{ matrix.os }} (Clang ${{matrix.clang-version }}) (${{ matrix.BUILD_TYPE}} Build)
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -yq --no-install-recommends \
                               clang-${{ matrix.clang-version }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-clang-${{ matrix.clang-version }}
          max-size: 50M

      - name: Configure CMake
        run: |
          cmake -B${{ github.workspace }}/build \
                -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                -G"Unix Makefiles"
        env:
          CC: clang-${{ matrix.clang-version }}
          CXX: clang++-${{ matrix.clang-version }}

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build \
                --config ${{ matrix.BUILD_TYPE }} \
                -- -j2
